### ISSUE TITLE
texture error

### ISSUE THREAD

**Issue by sebastiiaaannnn** [Kaomc/Ghoulcraft-BE-Garden-Pack#1]
um i think i have a problem using it.
when i apply this to a world, all the textures of every block turns black- do you know anything i could do to fix this?

**Comment by Kaomc** [comment]
This issue is caused by low memory into some mobile devices. This is also a bug on Minecraft Bedrock's new `1.16.210` update. This issue is unfixable as it's a client side problem.

Please do not ask for help in the `Issue` section of this repository. Direct questions into our [Discord](https://discord.gg/3QSE4mDqQd).
