### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by esprungjay** [Kaomc/Ghoulcraft-BE-Garden-Pack#2]
I have a problem as well Everything is Black when I Activate it in my world But my device has a Bigger storage and my Minecraft had a latest update...pls sort this out :< i really love it so much

**Comment by Kaomc** [comment]
This issue is caused by low memory into some mobile devices. This is also a bug on Minecraft Bedrock's new `1.16.210` update. A good device doesn't mean that the pack will work well on your game, this pack is designed to be used on Windows 10 Edition. This issue is unfixable as it's a client side problem.

Please do not ask for help in the `Issue` section of this repository. Direct questions into our [Discord](https://discord.gg/3QSE4mDqQd).
